INSERT INTO zup_magic.player VALUES (1,'p1',20,20,'PLAYER');
INSERT INTO zup_magic.player VALUES (2,'CPU',20,20,'COMPUTER');
INSERT INTO zup_magic.player_deck VALUES (1,1);
INSERT INTO zup_magic.player_deck VALUES (2,10);
INSERT INTO zup_magic.game VALUES (1,0,'CPU','PROGRESS',0);
INSERT INTO zup_magic.game_deck_cpu VALUES (1,11);
INSERT INTO zup_magic.game_deck_players VALUES (1,2);
INSERT INTO zup_magic.players_game VALUES (1,1);
INSERT INTO zup_magic.players_game VALUES (2,1);