version: '3.1'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zup_magic_manager
      POSTGRES_USER: zup_magic_manager
      POSTGRES_PASSWORD: zup_magic_manager
    volumes:
      - ./postgres-create-schemas.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - custom

networks:
  custom:
    driver: bridge